### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by Polarite** [colbiedison/compactmachines-fabric#1]
is there a compiled version I can use or a way to compile this, tried forjing and making github compile but it gave an error

**Comment by colbiedison** [comment]
Clone the repository, open a command prompt/terminal and execute `./gradlew build` (linux) or `gradlew.bat build` (windows).
The mod will be put in build/libs/. You'll want the one called `compactmachines-fabric-1.0-SNAPSHOT.jar`.

**Comment by colbiedison** [comment]
Here's a jar built from the [latest commit](https://github.com/colbiedison/compactmachines-fabric/commit/92b598dd9c8fd33fbc50eabbfe78d9c40df633cc).

[compactmachines-fabric-1.0-SNAPSHOT.jar.zip](https://github.com/colbiedison/compactmachines-fabric/files/8543658/compactmachines-fabric-1.0-SNAPSHOT.jar.zip)
