### ISSUE TITLE
gradlew not recognized

### ISSUE THREAD

**Issue by DistendedDev** [colbiedison/compactmachines-fabric#2]
![image](https://user-images.githubusercontent.com/94454399/159258082-90981b70-1487-49ea-aab9-eb3b58971bb2.png)

This error appears when i try to run a gradlew command, i believe that is because of the absence of gradle_wrapper.jar or gradlew.bat.

**Comment by colbiedison** [comment]
Whoops, I didn't include the gradle wrapper in the repository. [This](https://github.com/colbiedison/compactmachines-fabric/commit/92b598dd9c8fd33fbc50eabbfe78d9c40df633cc) should fix it.
